compressionLevel: mixed

nodeLinker: node-modules

logFilters:
  # Ignores some known warnings about the react/react-dom versions not satisfying @gumlet/react-hls-player
  - pattern: "*(paf38f)*"
    level: discard
  - pattern: "*(p741fc)*"
    level: discard
